apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user.fullname" . }}
data:
  REDIS_HOST: {{ .Values.configmap.REDIS_HOST }}
  CATALOGUE_HOST: {{ .Values.configmap.CATALOGUE_HOST }}
  CATALOGUE_PORT: "{{ .Values.configmap.CATALOGUE_PORT }}"
